features:
  - name: r_5
    expr: "pct_change(close, 5)"
    clip: [-0.2, 0.2]
    zscore_window: 120
  - name: atr_norm
    expr: "atr(high, low, close, 14)"
    clip: [0, 0.2]
    zscore_window: 120
targets: []
