name: Hourly Train & Daily Notify
on:
  schedule:
    - cron: "15 * * * 1-5"
  workflow_dispatch: {}
jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Run pipeline
        env:
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_CHAT_ID:  ${{ secrets.TG_CHAT_ID }}
        run: |
          python - <<'PY'
          import sys
          from pathlib import Path
          if (Path("src")).exists():
              sys.path.append("src")
          from entrypoints import daily_update, eod_task, periodic_reports_task, after_run_housekeeping
          from pipeline import run_paper_session
          print(">> daily_update()"); daily_update()
          print(">> run_paper_session()"); run_paper_session(top_k=5)
          print(">> eod_task()"); eod_task()
          print(">> periodic_reports_task()"); periodic_reports_task()
          print(">> after_run_housekeeping()"); after_run_housekeeping()
          PY
