name: Test Telegram
on:
  workflow_dispatch: {}   # allows manual run
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Send test message
        run: |
          curl -s -X POST https://api.telegram.org/bot${{ secrets.TG_BOT_TOKEN }}/sendMessage \
            -d chat_id=${{ secrets.TG_CHAT_ID }} \
            -d text="✅ Hello from GitHub Actions — your secrets are working!"
